[features]
seeds = false

[programs.devnet]
tiktok_clone = "Az4edEtU6JtghfueC4hS7Fo5fG3evPY5VUt6YbNHmhaN"

[programs.localnet]
tiktok_clone = "Grgf27wBA8E43gzAiMBvh6hoj7SBay24E4b636zgtJ4a"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
#cluster = "localnet"

wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
start = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 app/start.ts"
